// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package queue

type StringQueue struct {
	items []string
}

func MewStringQueue() *StringQueue {
	return &StringQueue{
		items: make([]string, 0),
	}
}

func (q *StringQueue) Push(item string) {
	q.items = append(q.items, item)
}

func (q *StringQueue) Pop() string {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}

type IntQueue struct {
	items []int
}

func MewIntQueue() *IntQueue {
	return &IntQueue{
		items: make([]int, 0),
	}
}

func (q *IntQueue) Push(item int) {
	q.items = append(q.items, item)
}

func (q *IntQueue) Pop() int {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}

type Float64Queue struct {
	items []float64
}

func MewFloat64Queue() *Float64Queue {
	return &Float64Queue{
		items: make([]float64, 0),
	}
}

func (q *Float64Queue) Push(item float64) {
	q.items = append(q.items, item)
}

func (q *Float64Queue) Pop() float64 {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
